[build]
  # No build command is needed for a static HTML site
  command = ""
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
